# coding: utf-8

"""
    Management API

    Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to version 1 of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v1/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v1 ```  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: developer-experience@adyen.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.terminal_orders_company_level_api import TerminalOrdersCompanyLevelApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTerminalOrdersCompanyLevelApi(unittest.TestCase):
    """TerminalOrdersCompanyLevelApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.terminal_orders_company_level_api.TerminalOrdersCompanyLevelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_companies_company_id_billing_entities(self):
        """Test case for get_companies_company_id_billing_entities

        Get a list of billing entities  # noqa: E501
        """
        pass

    def test_get_companies_company_id_shipping_locations(self):
        """Test case for get_companies_company_id_shipping_locations

        Get a list of shipping locations  # noqa: E501
        """
        pass

    def test_get_companies_company_id_terminal_models(self):
        """Test case for get_companies_company_id_terminal_models

        Get a list of terminal models  # noqa: E501
        """
        pass

    def test_get_companies_company_id_terminal_orders(self):
        """Test case for get_companies_company_id_terminal_orders

        Get a list of orders  # noqa: E501
        """
        pass

    def test_get_companies_company_id_terminal_orders_order_id(self):
        """Test case for get_companies_company_id_terminal_orders_order_id

        Get an order  # noqa: E501
        """
        pass

    def test_get_companies_company_id_terminal_products(self):
        """Test case for get_companies_company_id_terminal_products

        Get a list of terminal products  # noqa: E501
        """
        pass

    def test_patch_companies_company_id_terminal_orders_order_id(self):
        """Test case for patch_companies_company_id_terminal_orders_order_id

        Update an order  # noqa: E501
        """
        pass

    def test_post_companies_company_id_shipping_locations(self):
        """Test case for post_companies_company_id_shipping_locations

        Create a shipping location  # noqa: E501
        """
        pass

    def test_post_companies_company_id_terminal_orders(self):
        """Test case for post_companies_company_id_terminal_orders

        Create an order  # noqa: E501
        """
        pass

    def test_post_companies_company_id_terminal_orders_order_id_cancel(self):
        """Test case for post_companies_company_id_terminal_orders_order_id_cancel

        Cancel an order  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
