# coding: utf-8

"""
    Management API

    Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to version 1 of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v1/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v1 ```  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: developer-experience@adyen.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.list_company_response import ListCompanyResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestListCompanyResponse(unittest.TestCase):
    """ListCompanyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListCompanyResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCompanyResponse`
        """
        model = openapi_client.models.list_company_response.ListCompanyResponse()  # noqa: E501
        if include_optional :
            return ListCompanyResponse(
                links = openapi_client.models.pagination_links.PaginationLinks(
                    first = openapi_client.models.links_element.LinksElement(
                        href = '', ), 
                    last = openapi_client.models.links_element.LinksElement(
                        href = '', ), 
                    next = , 
                    prev = , 
                    self = , ), 
                data = [
                    openapi_client.models.company.Company(
                        _links = openapi_client.models.company_links.CompanyLinks(
                            api_credentials = openapi_client.models.links_element.LinksElement(
                                href = '', ), 
                            self = openapi_client.models.links_element.LinksElement(
                                href = '', ), 
                            users = , 
                            webhooks = , ), 
                        data_centers = [
                            openapi_client.models.data_center.DataCenter(
                                live_prefix = '', 
                                name = '', )
                            ], 
                        description = '', 
                        id = '', 
                        name = '', 
                        reference = '', 
                        status = '', )
                    ], 
                items_total = 56, 
                pages_total = 56
            )
        else :
            return ListCompanyResponse(
                items_total = 56,
                pages_total = 56,
        )
        """

    def testListCompanyResponse(self):
        """Test ListCompanyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
