# coding: utf-8

"""
    Management API

    Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to version 1 of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v1/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v1 ```  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: developer-experience@adyen.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.payment_methods_merchant_level_api import PaymentMethodsMerchantLevelApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPaymentMethodsMerchantLevelApi(unittest.TestCase):
    """PaymentMethodsMerchantLevelApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.payment_methods_merchant_level_api.PaymentMethodsMerchantLevelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_merchants_merchant_id_payment_method_settings(self):
        """Test case for get_merchants_merchant_id_payment_method_settings

        Get all payment methods  # noqa: E501
        """
        pass

    def test_get_merchants_merchant_id_payment_method_settings_payment_method_id(self):
        """Test case for get_merchants_merchant_id_payment_method_settings_payment_method_id

        Get payment method details  # noqa: E501
        """
        pass

    def test_get_merchants_merchant_id_payment_method_settings_payment_method_id_get_apple_pay_domains(self):
        """Test case for get_merchants_merchant_id_payment_method_settings_payment_method_id_get_apple_pay_domains

        Get Apple Pay domains  # noqa: E501
        """
        pass

    def test_patch_merchants_merchant_id_payment_method_settings_payment_method_id(self):
        """Test case for patch_merchants_merchant_id_payment_method_settings_payment_method_id

        Update a payment method  # noqa: E501
        """
        pass

    def test_post_merchants_merchant_id_payment_method_settings(self):
        """Test case for post_merchants_merchant_id_payment_method_settings

        Request a payment method  # noqa: E501
        """
        pass

    def test_post_merchants_merchant_id_payment_method_settings_payment_method_id_add_apple_pay_domains(self):
        """Test case for post_merchants_merchant_id_payment_method_settings_payment_method_id_add_apple_pay_domains

        Add an Apple Pay domain  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
