# coding: utf-8

"""
    Management API

    Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to version 1 of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v1/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v1 ```  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: developer-experience@adyen.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class Contact(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    email: Optional[StrictStr] = Field(None, description="The individual's email address.")
    first_name: Optional[StrictStr] = Field(None, alias="firstName", description="The individual's first name.")
    infix: Optional[StrictStr] = Field(None, description="The infix in the individual's name, if any.")
    last_name: Optional[StrictStr] = Field(None, alias="lastName", description="The individual's last name.")
    phone_number: Optional[StrictStr] = Field(None, alias="phoneNumber", description="The individual's phone number, specified as 10-14 digits with an optional `+` prefix.")
    __properties = ["email", "firstName", "infix", "lastName", "phoneNumber"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Contact:
        """Create an instance of Contact from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Contact:
        """Create an instance of Contact from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return Contact.parse_obj(obj)

        _obj = Contact.parse_obj({
            "email": obj.get("email"),
            "first_name": obj.get("firstName"),
            "infix": obj.get("infix"),
            "last_name": obj.get("lastName"),
            "phone_number": obj.get("phoneNumber")
        })
        return _obj

