# coding: utf-8

"""
    Management API

    Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to version 1 of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v1/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v1 ```  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: developer-experience@adyen.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, constr, validator

class KlarnaInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    auto_capture: Optional[StrictBool] = Field(None, alias="autoCapture", description="Indicates the status of [Automatic capture](https://docs.adyen.com/online-payments/capture#automatic-capture). Default value: **false**.")
    dispute_email: StrictStr = Field(..., alias="disputeEmail", description="The email address for disputes.")
    region: constr(strict=True, max_length=2, min_length=2) = Field(..., description="The region of operation. For example, **NA**, **EU**, **CH**, **AU**.")
    support_email: StrictStr = Field(..., alias="supportEmail", description="The email address of merchant support.")
    __properties = ["autoCapture", "disputeEmail", "region", "supportEmail"]

    @validator('region')
    def region_validate_enum(cls, v):
        if v not in ('NA', 'EU', 'CH', 'AU'):
            raise ValueError("must validate the enum values ('NA', 'EU', 'CH', 'AU')")
        return v

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> KlarnaInfo:
        """Create an instance of KlarnaInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> KlarnaInfo:
        """Create an instance of KlarnaInfo from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return KlarnaInfo.parse_obj(obj)

        _obj = KlarnaInfo.parse_obj({
            "auto_capture": obj.get("autoCapture"),
            "dispute_email": obj.get("disputeEmail"),
            "region": obj.get("region"),
            "support_email": obj.get("supportEmail")
        })
        return _obj

