# coding: utf-8

"""
    Management API

    Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to version 1 of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v1/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v1 ```  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: developer-experience@adyen.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr
from openapi_client.models.address2 import Address2
from openapi_client.models.store_split_configuration import StoreSplitConfiguration

class StoreCreationWithMerchantCodeRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    address: Address2 = ...
    business_line_ids: Optional[List[StrictStr]] = Field(None, alias="businessLineIds", description="The unique identifiers of the [business lines](https://docs.adyen.com/api-explorer/#/legalentity/latest/post/businesslines__resParam_id) that the store is associated with. If not specified, the business line of the merchant account is used. Required when there are multiple business lines under the merchant account.")
    description: StrictStr = Field(..., description="Your description of the store.")
    external_reference_id: Optional[StrictStr] = Field(None, alias="externalReferenceId", description="When using the Zip payment method: The location ID that Zip has assigned to your store.")
    merchant_id: StrictStr = Field(..., alias="merchantId", description="The unique identifier of the merchant account that the store belongs to.")
    phone_number: StrictStr = Field(..., alias="phoneNumber", description="The phone number of the store, including '+' and country code.")
    reference: Optional[StrictStr] = Field(None, description="Your reference to recognize the store by. Also known as the store code.  Allowed characters: Lowercase and uppercase letters without diacritics, numbers 0 through 9, hyphen (-), and underscore (_).")
    shopper_statement: StrictStr = Field(..., alias="shopperStatement", description="The store name to be shown on the shopper's bank or credit card statement and on the shopper receipt. Maximum length: 22 characters; can't be all numbers.")
    split_configuration: Optional[StoreSplitConfiguration] = Field(None, alias="splitConfiguration")
    __properties = ["address", "businessLineIds", "description", "externalReferenceId", "merchantId", "phoneNumber", "reference", "shopperStatement", "splitConfiguration"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StoreCreationWithMerchantCodeRequest:
        """Create an instance of StoreCreationWithMerchantCodeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of split_configuration
        if self.split_configuration:
            _dict['splitConfiguration'] = self.split_configuration.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StoreCreationWithMerchantCodeRequest:
        """Create an instance of StoreCreationWithMerchantCodeRequest from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return StoreCreationWithMerchantCodeRequest.parse_obj(obj)

        _obj = StoreCreationWithMerchantCodeRequest.parse_obj({
            "address": Address2.from_dict(obj.get("address")) if obj.get("address") is not None else None,
            "business_line_ids": obj.get("businessLineIds"),
            "description": obj.get("description"),
            "external_reference_id": obj.get("externalReferenceId"),
            "merchant_id": obj.get("merchantId"),
            "phone_number": obj.get("phoneNumber"),
            "reference": obj.get("reference"),
            "shopper_statement": obj.get("shopperStatement"),
            "split_configuration": StoreSplitConfiguration.from_dict(obj.get("splitConfiguration")) if obj.get("splitConfiguration") is not None else None
        })
        return _obj

