# coding: utf-8

"""
    Management API

    Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to version 1 of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v1/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v1 ```  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: developer-experience@adyen.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, validator
from openapi_client.models.store_split_configuration import StoreSplitConfiguration
from openapi_client.models.updatable_address import UpdatableAddress

class UpdateStoreRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    address: Optional[UpdatableAddress] = None
    business_line_ids: Optional[List[StrictStr]] = Field(None, alias="businessLineIds", description="The unique identifiers of the [business lines](https://docs.adyen.com/api-explorer/#/legalentity/latest/post/businesslines__resParam_id) that the store is associated with.")
    description: Optional[StrictStr] = Field(None, description="The description of the store.")
    external_reference_id: Optional[StrictStr] = Field(None, alias="externalReferenceId", description="When using the Zip payment method: The location ID that Zip has assigned to your store.")
    split_configuration: Optional[StoreSplitConfiguration] = Field(None, alias="splitConfiguration")
    status: Optional[StrictStr] = Field(None, description="The status of the store. Possible values are:  - **active**: This value is assigned automatically when a store is created.  - **inactive**: The maximum [transaction limits and number of Store-and-Forward transactions](https://docs.adyen.com/point-of-sale/determine-account-structure/configure-features#payment-features) for the store are set to 0. This blocks new transactions, but captures are still possible. - **closed**: The terminals of the store are reassigned to the merchant inventory, so they can't process payments.  You can change the status from **active** to **inactive**, and from **inactive** to **active** or **closed**.  Once **closed**, a store can't be reopened.")
    __properties = ["address", "businessLineIds", "description", "externalReferenceId", "splitConfiguration", "status"]

    @validator('status')
    def status_validate_enum(cls, v):
        if v is None:
            return v

        if v not in ('active', 'closed', 'inactive'):
            raise ValueError("must validate the enum values ('active', 'closed', 'inactive')")
        return v

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateStoreRequest:
        """Create an instance of UpdateStoreRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of split_configuration
        if self.split_configuration:
            _dict['splitConfiguration'] = self.split_configuration.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateStoreRequest:
        """Create an instance of UpdateStoreRequest from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return UpdateStoreRequest.parse_obj(obj)

        _obj = UpdateStoreRequest.parse_obj({
            "address": UpdatableAddress.from_dict(obj.get("address")) if obj.get("address") is not None else None,
            "business_line_ids": obj.get("businessLineIds"),
            "description": obj.get("description"),
            "external_reference_id": obj.get("externalReferenceId"),
            "split_configuration": StoreSplitConfiguration.from_dict(obj.get("splitConfiguration")) if obj.get("splitConfiguration") is not None else None,
            "status": obj.get("status")
        })
        return _obj

